name: Run Tests

on: push
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.0'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
      - name: Deploy to <your domain>
        uses: appleboy/ssh-action@master
        with:
            username: root
            host: 209.38.224.47
            password: ${{ secrets.SERVER_PASSWORD }}
            script: 'cd /var/www/farm-site && git pull && sudo systemctl restart your_app.service'
